"""Add unique constraint to positions.

Revision ID: 441b4b9fc5e8
Revises: 6cec9828deda
Create Date: 2024-08-17 09:34:51.109932

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "441b4b9fc5e8"
down_revision = "6cec9828deda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "positions_fpl_id_season_key", ["fpl_id", "season"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_constraint("positions_fpl_id_season_key", type_="unique")

    # ### end Alembic commands ###
