"""Add season to player stats.

Revision ID: 77a166b6cfab
Revises: 7abb62dc2072
Create Date: 2024-08-14 12:01:19.698850

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77a166b6cfab"
down_revision = "7abb62dc2072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_stats", sa.Column("season", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE player_stats SET season=0")
    op.alter_column("player_stats", "season", nullable=False)

    with op.batch_alter_table("stat_details", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stat_details", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("player_stats", schema=None) as batch_op:
        batch_op.drop_column("season")

    # ### end Alembic commands ###
