"""Add unique constraint on player stats.

Revision ID: 922abbe6544e
Revises: 628ad57a5e52
Create Date: 2024-08-15 22:45:23.460500

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "922abbe6544e"
down_revision = "628ad57a5e52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_stats", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            constraint_name="player_stats_player_id_season_key",
            columns=["player_id", "season"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_stats", schema=None) as batch_op:
        batch_op.drop_constraint(
            constraint_name="player_stats_player_id_season_key", type_="unique"
        )

    # ### end Alembic commands ###
