"""Update gameweek to support timestamp types.

Revision ID: bc190cfbc015
Revises: 687a81484bb8
Create Date: 2024-08-15 14:45:20.340612

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc190cfbc015"
down_revision = "687a81484bb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gameweeks", schema=None) as batch_op:
        batch_op.alter_column(
            "deadline_time",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            postgresql_using="deadline_time::timestamp",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "release_time",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            postgresql_using="deadline_time::timestamp",
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gameweeks", schema=None) as batch_op:
        batch_op.alter_column(
            "release_time",
            existing_type=sa.DateTime(),
            type_=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "deadline_time",
            existing_type=sa.DateTime(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
