"""Add gameweek relationship on fixture.

Revision ID: c2cfd4d8096d
Revises: bc190cfbc015
Create Date: 2024-08-15 16:03:35.328623

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2cfd4d8096d"
down_revision = "bc190cfbc015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.alter_column("gameweek", new_column_name="gameweek_id")
        batch_op.alter_column("team_a", new_column_name="team_a_id")
        batch_op.alter_column("team_h", new_column_name="team_h_id")

    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column("team", new_column_name="team_id")
        batch_op.alter_column("position", new_column_name="position_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column("team_id", new_column_name="team")
        batch_op.alter_column("position_id", new_column_name="position")

    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.alter_column("gameweek_id", new_column_name="gameweek")
        batch_op.alter_column("team_a_id", new_column_name="team_a")
        batch_op.alter_column("team_h_id", new_column_name="team_h")

    # ### end Alembic commands ###
