"""Update top player for a gameweek.

Revision ID: c99e5c4a209a
Revises: 922abbe6544e
Create Date: 2024-08-16 13:45:05.707200

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c99e5c4a209a"
down_revision = "922abbe6544e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gameweeks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("top_player_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "gameweeks_top_player_id_fkey", "players", ["top_player_id"], ["id"]
        )
        batch_op.drop_column("top_element")
        batch_op.drop_column("top_element_info")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gameweeks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "top_element_info",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("top_element", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint("gameweeks_top_player_id_fkey", type_="foreignkey")
        batch_op.drop_column("top_player_id")

    # ### end Alembic commands ###
