"""Initial migration.

Revision ID: ed2b633cfd35
Revises: 
Create Date: 2024-08-13 10:41:39.226533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b633cfd35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameweeks',
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('average_entry_score', sa.Integer(), nullable=False),
    sa.Column('data_checked', sa.Boolean(), nullable=False),
    sa.Column('deadline_time', sa.String(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_next', sa.Boolean(), nullable=False),
    sa.Column('is_previous', sa.Boolean(), nullable=False),
    sa.Column('ranked_count', sa.Integer(), nullable=False),
    sa.Column('transfers_made', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('highest_scoring_entry', sa.Integer(), nullable=True),
    sa.Column('most_captained', sa.Integer(), nullable=True),
    sa.Column('most_selected', sa.Integer(), nullable=True),
    sa.Column('most_transferred_in', sa.Integer(), nullable=True),
    sa.Column('most_vice_captained', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.String(), nullable=True),
    sa.Column('top_element', sa.Integer(), nullable=True),
    sa.Column('top_element_info', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('plural_name', sa.String(), nullable=False),
    sa.Column('plural_name_short', sa.String(), nullable=False),
    sa.Column('singular_name', sa.String(), nullable=False),
    sa.Column('singular_name_short', sa.String(), nullable=False),
    sa.Column('squad_select', sa.Integer(), nullable=False),
    sa.Column('squad_min_play', sa.Integer(), nullable=False),
    sa.Column('squad_max_play', sa.Integer(), nullable=False),
    sa.Column('ui_shirt_specific', sa.Boolean(), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_details',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('draw', sa.Integer(), nullable=False),
    sa.Column('loss', sa.Integer(), nullable=False),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('team_division', sa.Integer(), nullable=True),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=False),
    sa.Column('strength_overall_away', sa.Integer(), nullable=False),
    sa.Column('strength_attack_home', sa.Integer(), nullable=False),
    sa.Column('strength_attack_away', sa.Integer(), nullable=False),
    sa.Column('strength_defence_home', sa.Integer(), nullable=False),
    sa.Column('strength_defence_away', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tinkers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('finished_provisional', sa.Boolean(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('provisional_start_time', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('team_a_difficulty', sa.Integer(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_h_difficulty', sa.Integer(), nullable=False),
    sa.Column('team_h_score', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.Integer(), nullable=False),
    sa.Column('team_h', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['gameweek'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['team_a'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('web_name', sa.String(), nullable=False),
    sa.Column('squad_number', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('news', sa.String(), nullable=False),
    sa.Column('news_added', sa.Boolean(), nullable=True),
    sa.Column('penalties_order', sa.Integer(), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('corners_and_indirect_freekicks_order', sa.Integer(), nullable=True),
    sa.Column('corners_and_indirect_freekicks_text', sa.String(), nullable=True),
    sa.Column('direct_freekicks_order', sa.Integer(), nullable=False),
    sa.Column('direct_freekicks_text', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['position'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bps', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('clean_sheets_per_90', sa.Integer(), nullable=False),
    sa.Column('cost_change_event', sa.Integer(), nullable=False),
    sa.Column('cost_change_event_fall', sa.Integer(), nullable=False),
    sa.Column('cost_change_start', sa.Integer(), nullable=False),
    sa.Column('cost_change_start_fall', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.String(), nullable=False),
    sa.Column('dreamteam_count', sa.Integer(), nullable=False),
    sa.Column('event_points', sa.Integer(), nullable=False),
    sa.Column('expected_assists', sa.String(), nullable=False),
    sa.Column('expected_assists_per_90', sa.Integer(), nullable=False),
    sa.Column('expected_goal_involvements', sa.String(), nullable=False),
    sa.Column('expected_goal_involvements_per_90', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.String(), nullable=False),
    sa.Column('expected_goals_per_90', sa.Integer(), nullable=False),
    sa.Column('expected_goals_conceded', sa.String(), nullable=False),
    sa.Column('expected_goals_conceded_per_90', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('goals_conceded_per_90', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('ict_index', sa.String(), nullable=False),
    sa.Column('influence', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('points_per_game', sa.String(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('saves_per_90', sa.Integer(), nullable=False),
    sa.Column('selected_by_percent', sa.String(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('starts_per_90', sa.Integer(), nullable=False),
    sa.Column('threat', sa.String(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('transfers_in', sa.Integer(), nullable=False),
    sa.Column('transfers_in_event', sa.Integer(), nullable=False),
    sa.Column('transfers_out', sa.Integer(), nullable=False),
    sa.Column('transfers_out_event', sa.Integer(), nullable=False),
    sa.Column('value_form', sa.String(), nullable=False),
    sa.Column('value_season', sa.String(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('players')
    op.drop_table('fixtures')
    op.drop_table('weightings')
    op.drop_table('tinkers')
    op.drop_table('teams')
    op.drop_table('stat_details')
    op.drop_table('positions')
    op.drop_table('gameweeks')
    op.drop_table('fixture_stats')
    # ### end Alembic commands ###
