"""Add configurations table.

Revision ID: edd961afb15c
Revises: 77a166b6cfab
Create Date: 2024-08-14 13:12:28.366506

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "edd961afb15c"
down_revision = "77a166b6cfab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("BOOLEAN", "STRING", "INTEGER", name="configurationtypes"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="configurations_pkey"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configurations")
    # ### end Alembic commands ###
